version: '3.9'

services:
  server:
    container_name: client
    build:
      context: .
      dockerfile: Dockerfile
    image: thediep094/client:latest
    restart: always
    ports:
      - "3030:3000"